#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$HOME/debforge-aarch64"
FMT="$ROOT/formats/manpage.spec"
PROJ="$ROOT/var/lib/debforge/project.db"
STAGE="$ROOT/runtime/stage"
LOG="$ROOT/logs/manpage.log"

ts(){ date +"%Y-%m-%d %H:%M:%S"; }
log(){ printf "[%s][MANPAGE] %s\n" "$(ts)" "$*" >> "$LOG"; }

kv(){
  grep -E "^$1=" "$PROJ" | cut -d= -f2-
}

generate(){
  local name sec
  name="$(kv PROJECT_NAME)"
  sec=1
  local out="$STAGE/usr/share/man/man$sec/$name.$sec"
  mkdir -p "$(dirname "$out")"
  {
    printf ".TH %s %s\n" "$name" "$sec"
    printf ".SH NAME\n%s\n" "$name"
    printf ".SH SYNOPSIS\n%s\n" "$name"
    printf ".SH DESCRIPTION\nGenerated by DebForge\n"
  } > "$out"
  gzip -f "$out"
}

main(){
  log "start"
  generate
  log "done"
}

main "$@"
